### ISSUE TITLE
EKS configuration

### ISSUE THREAD

**Issue by mthomsit** [gocd/kubernetes-elastic-agents#100]
We are experiencing the same issue running GoCD and the Elastic Agents plugin under EKS as described in 
https://github.com/gocd/kubernetes-elastic-agents/issues/81

We have GoCD installed via helm and have configured:

- aws-alb-ingress-controller
- a service account in the gocd namespace with cluster-admin role bindings
- external-dns via cloudflare

using the following values

```
server:
  ingress:
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      external-dns.alpha.kubernetes.io/hostname: [removed]
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/certificate-arn: [arn removed]
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    hosts:
    - [removed]
```

and settings

```
--set rbac.roleRef=cluster-admin --set serviceAccount.create=true --set serviceAccount.name=gocd --set server.persistence.existingClaim=gocd-pv-claim
```

Trying to save the plugin settings shows "Failed validation of plugin settings. The reasons could be - Cluster Url is configured incorrectly or the service account token might not have enough permissions to get namespaces or incorrect CA certificate.Please check the plugin log for more details."

and the logs show

```
2019-04-09 11:17:13,334 ERROR [156@MessageListener for ServerPingListener] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:128 [plugin-cd.go.contrib.elasticagent.kubernetes] - Failed to handle request cd.go.elastic-agent.server-ping
java.lang.RuntimeException: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.100.0.1/api/v1/namespaces/gocd/pods. Message: Unauthorized! Configured service account doesn't have access. Service account may have been revoked. Unauthorized.
```

GoCD Server URL, Cluster URL, Namespace and Security token are set.  Cluster ca certificate data is not. 

Setting those attributes by following the steps in notes shows the same error.

Any help would be very welcome.  Thank you in advance
