### ISSUE TITLE
Use other env variable in elastic agent pod name than POD_POSTFIX

### ISSUE THREAD

**Issue by vitaliby** [gocd/kubernetes-elastic-agents#201]
While creating an elastic agent profile I can add POD_POSTFIX env variable to pod name, but is it possible to add any other env variables? I would like to have something like `nonprd-agent-{{ GO_PIPELINE_NAME }}-{{ POD_POSTFIX }}` as a pod name, where GO_PIPELINE_NAME is a pipeline name running by agent.

```
apiVersion: v1  
kind: Pod  
metadata:  
  name: nonprd-agent-{{ GO_PIPELINE_NAME }}-{{ POD_POSTFIX }}  
  labels:  
    app: gocd-agent  
spec:  
  containers:  
    - name: gocd-agent-container-{{ GO_PIPELINE_NAME }}-{{ CONTAINER_POSTFIX }}  
```
