### ISSUE TITLE
Provide a support for private docker registry

### ISSUE THREAD

**Issue by bdpiparva** [gocd/kubernetes-elastic-agents#38]
Currently, the plugin is pulling docker images from `hub.docker.com`. Provide way to pull a docker image from private registry.

**Comment by Mark-McCracken** [comment]
This can be done by specifying imagePullSecrets in the pod spec I think?

**Comment by arvindsv** [comment]
@Mark-McCracken If it's possible, then I think we should document it. Have you tried it?

/cc @sheroy Maybe we should try it and document it somewhere? https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/

**Comment by varshavaradarajan** [comment]
@arvindsv - https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ . Specifically https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-pod-that-uses-your-secret can be of use for your documentation.

**Comment by Mark-McCracken** [comment]
Yes I have :)

I really liked the gocd/gocd-agent-docker-dind image. But I wanted to extend it to be able to easily interact with jfrog's artifactory by using the CLI in my scripts (Not specifically a docker registry, just anything).

So I made a dockerfile like this:

```bash
ARG GOCD_DIND_VERSION_TAG
FROM gocd/gocd-agent-docker-dind:${GOCD_DIND_VERSION_TAG}

RUN apk add --no-cache --virtual .build-deps bash gcc musl-dev openssl go && \
	wget -O go.tgz https://dl.google.com/go/go1.11.5.src.tar.gz && \
	tar -C /usr/local -xzf go.tgz && \
	cd /usr/local/go/src/ && \
	./make.bash && \
	export PATH="/usr/local/go/bin:$PATH" && \
	export GOPATH=/opt/go/ && \
	export PATH=$PATH:$GOPATH/bin && \
	apk del .build-deps && \
	apk add build-base && \
	cd /usr/local/ && \
	git clone https://github.com/jfrog/jfrog-cli-go/ && \
	cd jfrog-cli-go/jfrog-cli/jfrog/ && \
	go build && \
	mv jfrog /usr/bin/

# should I put any effort in to optimise this to make it smaller?
# Can use multi-stage builds, but don't know which things can be removed though.

ENTRYPOINT ["/docker-entrypoint.sh"] # this is just the same entrypoint from GoCD's image mentioned above
```

I built this image and pushed it to my private docker container registry.

Then I created a kubernetes secret of type docker registry, like this:

```bash
kubectl create secret docker-registry \
	my-docker-registry \
	--namespace gocd \
	--docker-server=my-private-repo.co.uk \
	--docker-username="$(cat username.txt)" \
	--docker-password="$(cat password.txt)" \
	--docker-email=my@emailaddress.co.uk
```

Then my kubernetes elastic agent podfile looks like the following:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gocd-agent-{{ POD_POSTFIX }}
  labels:
    app: web
spec:
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: my-private-repo.co.uk/docker-jfrog:v19.1.0
      securityContext:
        privileged: true
      volumeMounts:
      - name: ssh-secrets
        readOnly: true
        mountPath: /home/go/.ssh
      - name: artifactory-credentials
        readOnly: true
        mountPath: /home/go/.jfrog
  imagePullSecrets:
    - name: my-docker-registry
  volumes:
  - name: ssh-secrets
    secret:
      secretName: gocd-agent-ssh-keys
  - name: artifactory-credentials
    secret:
      secretName: artifactory-credentials
```

And then I use the image just like normal.
Here's an example pipeline:

```yaml
format_version: 3
pipelines:
  docker-jfrog-gcloud:
    group: "Platform-Base_Images"
    label_template: ${COUNT}
    materials:
      github:
        git: git@github.mycompany.co.uk:Org/repo.git
        whitelist:
          - custom-images/docker-jfrog-gcloud/**/*.*
    environment_variables:
      DOCKER_REGISTRY: "my-private-repo.co.uk"
      GOCD_DIND_VERSION_TAG: "v19.1.0"
      GOCD_GCLOUD_VERSION_TAG: "233.0.0"
    stages:
      - build:
          artifacts:
          - external:
              id: image
              store_id: jfrog_docker_artifactory
              configuration:
                options:
                  Image: "${DOCKER_REGISTRY}/${GO_PIPELINE_NAME}"
                  Tag: "${GOCD_DIND_VERSION_TAG}-${GOCD_GCLOUD_VERSION_TAG}"
          elastic_profile_id: "docker-jfrog"
          tasks:
            - script: ./custom-images/docker-jfrog-gcloud/build.sh
```

The above pipeline actually creates another base image that does something very similar, to create another gocd agent image that's been extended to easily interact with Google Cloud Platform.

Let me know if that helps!

Mark
