### ISSUE TITLE
With GoCD Version: 24.2.0 and Kubernetes Elastic Agent plugin: 4.1.0-541, agents are killed after 10 minutes, even when the job has not finished execution yet.

### ISSUE THREAD

**Issue by ivanpiyvikov** [gocd/kubernetes-elastic-agents#422]
We are experiencing an issue where agents are terminated after 10 minutes while jobs are still running. The setup is as follows:

- GoCD Version: 24.2.0
- Kubernetes Elastic Agent plugin: 4.1.0-541
- Environment: Kubernetes on AWS

Steps Taken:

- Configured auto_register_timeout with value > 10 min and < 10 min result is same 
- Adjusted resource limits
- Set up default Job Timeout to "Never job timeout"
- Other miscellaneous configurations

EKS-Cluster-Profile:

```
apiVersion: v1
kind: Pod
metadata:
  name: pod-gocd-prefix-{{ POD_POSTFIX }}
  namespace: gocd-agents
  labels:
    app: web
spec:
  restartPolicy: Never
  serviceAccountName: gocd-agent-sa
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: *.dkr.ecr.eu-west-1.amazonaws.com/gocd-agent-ubuntu:2.7.0-adf4049
      env:
      volumeMounts:
        - name: persistent-storage
          mountPath: /godata/pipelines
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-gocd-agent-claim
```

Despite these adjustments, the issue persists. We would appreciate any guidance or suggestions for further troubleshooting.
