### ISSUE TITLE
Provide an option to always pull the elastic agent docker image

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/kubernetes-elastic-agents#51]
Usually, docker images used with the elastic agents are versioned. So, if a new image needs to be used, the elastic profile is updated with the right tag and the jobs start to use the new image. If the tag is not versioned, the newer image is not pulled down.

Have image pull policies to either pull the elastic agent docker image always and to pull the image if not present on the machine.

**Comment by GaneshSPatil** [comment]
@varshavaradarajan -- can we use `pod yaml` to specify the pod configuration for the elastic profile?

for example:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-name-prefix-{{ POD_POSTFIX }}
  labels:
    app: web
spec:
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: {{ GOCD_AGENT_IMAGE }}:{{ LATEST_VERSION }}
      imagePullPolicy: Always
```
