### ISSUE TITLE
Does the elastic agent support  kubernetes PVC volume?

### ISSUE THREAD

**Issue by colachg** [gocd/kubernetes-elastic-agents#84]
Here is my pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-name-prefix-{{ POD_POSTFIX }}
  labels:
    app: web
spec:
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: gocd/gocd-agent-docker-dind:v18.12.0
      securityContext:
        privileged: true
      volumeMounts:
      - name: ssh-key-secret
        mountPath: /home/go/.ssh
        readOnly: true
  volumes:
  - name: ssh-key-secret
    secret:
      secretName: ssh-key-secret
```
when I change volumes.secret to `persistentVolumeClaim` and use correct claimName.Then I assign the elastic agent to a  job and I trigger the pipeline manually. But after a long time, the pod doesn't start and the job is still waiting...
